@echo off

SET IS_FOLDER_SRC=
SET IS_FILE_SRC=
SET IS_FOLDER_DST=
SET IS_FILE_DST=
SET SRC_PATH=
SET DST_PATH=
SET VIRTUAL_ENV_NAME=
SET PATH1=%PATH%

if %1*==* goto usage
if %1==deactivate goto deactivate
if %1==off goto deactivate
if %1==end goto deactivate
if NOT "%~1"=="" goto isdir
goto end

:usage
	ECHO USAGE: %~n0 [CURRENT_PYTHON_PATH] [DESTINATION_PYTHON_PATH]
goto end

:deactivate
	set VIRTUAL_ENV=
	SET IS_FOLDER_SRC=
	SET IS_FILE_SRC=
	SET IS_FOLDER_DST=
	SET IS_FILE_DST=
	SET SRC_PATH=
	SET DST_PATH=
	SET VIRTUAL_ENV_NAME=
	SET PATH=%PATH1%

	REM Don't use () to avoid problems with them in %PATH%
	if not defined _OLD_VIRTUAL_PROMPT goto ENDIFVPROMPT
	    set "PROMPT=%_OLD_VIRTUAL_PROMPT%"
	    set _OLD_VIRTUAL_PROMPT=
	:ENDIFVPROMPT

	if not defined _OLD_VIRTUAL_PYTHONHOME goto ENDIFVHOME
	    set "PYTHONHOME=%_OLD_VIRTUAL_PYTHONHOME%"
	    set _OLD_VIRTUAL_PYTHONHOME=
	:ENDIFVHOME

	if not defined _OLD_VIRTUAL_PATH goto ENDIFVPATH
	    set "PATH=%_OLD_VIRTUAL_PATH%"
	    set _OLD_VIRTUAL_PATH=
	:ENDIFVPATH

goto end

:isdir
	SET VIRTUAL_ENV_NAME=%~n2
	rem SETLOCAL ENABLEEXTENSIONS
	set ATTR=%~a1
	SET ATTR2=%~a2
	
	set DIRATTR=%ATTR:~0,1%
	set DIRATTR2=%ATTR2:~0,1%
	
	if /I "%DIRATTR%"=="d" (
		IF DEFINED CMD_DEBUG (echo %1 IS A FOLDER)
		SET IS_FOLDER_SRC=1
		SET SRC_PATH=%1
	) else (
		IF DEFINED CMD_DEBUG (echo %1 NOT A FOLDER)
		SET IS_FOLDER_SRC=
	)

	if /I "%DIRATTR2%"=="d" (
		IF DEFINED CMD_DEBUG (echo %2 IS A FOLDER)
		SET IS_FOLDER_DST=1
		SET DST_PATH=%2
		SET mypython=%2
	) else (
		IF DEFINED CMD_DEBUG (echo %2 NOT A FOLDER)
		SET IS_FOLDER_DST=
	)
	if DEFINED SRC_PATH (
		if DEFINED DST_PATH (
			goto SET_ENV
		) else (
			rem SET DST_PATH=%SRC_PATH%
			IF DEFINED CMD_DEBUG (echo %2 is NOT a VALID DIRECTORY)
			SET VIRTUAL_ENV_NAME=%~n1
			GOTO SET_ENV_COMMONS
		)
	) else (
		IF DEFINED CMD_DEBUG (echo %1 is NOT a VALID DIRECTORY)
	)

goto end

:SET_ENV

	set "VIRTUAL_ENV=%DST_PATH%"
	rem ECHO VIRTUAL_ENV0=%VIRTUAL_ENV%

	if defined _OLD_VIRTUAL_PROMPT (
	    set "PROMPT=%_OLD_VIRTUAL_PROMPT%"
	) else (
	    if not defined PROMPT (
	        set "PROMPT=$P$G"
	    )
	    set "_OLD_VIRTUAL_PROMPT=%PROMPT%"
	)

	IF DEFINED VIRTUAL_ENV_NAME (
		rem ECHO VIRTUAL_ENV_NAME=%VIRTUAL_ENV_NAME%
		set "PROMPT=[101;93m(%VIRTUAL_ENV_NAME%)[0m %PROMPT%"
		rem ECHO PROMPT0=%PROMPT%
	) else (
		rem ECHO PROMPT1=%PROMPT%
		SET /P VIRTUAL_ENV_NAME="VIRTUAL ENV NAME: "
	)

	if defined _OLD_VIRTUAL_PYTHONHOME goto ENDIFVHOME
	    set "_OLD_VIRTUAL_PYTHONHOME=%PYTHONHOME%"


:ENDIFVHOME
set PYTHONHOME=
if not defined _OLD_VIRTUAL_PATH goto ENDIFVPATH1
    set "PATH=%_OLD_VIRTUAL_PATH%"

:ENDIFVPATH1
if defined _OLD_VIRTUAL_PATH goto ENDIFVPATH2
    set "_OLD_VIRTUAL_PATH=%PATH%"

:ENDIFVPATH2
rem ECHO SRC_PATH=%SRC_PATH%
rem ECHO DST_PATH=%DST_PATH%
CALL SET PATH=%%PATH:%SRC_PATH%=%DST_PATH%%%
rem ECHO PATH=%PATH%
rem set "PATH=%VIRTUAL_ENV%\Scripts;%PATH%"
rem set PATH="%PATH:c:\ProgramData\Anaconda2=C:\ProgramData\Python37%"
goto end

:SET_ENV_COMMONS
	
	SET REPLACEMENT_01=c:\ProgramData\Anaconda2
	SET REPLACEMENT_02=c:\ProgramData\Python37
	SET REPLACEMENT_03=c:\Python37
	SET REPLACEMENT_04=c:\Python27
	SET REPLACEMENT_05=c:\Python26
	SET REPLACEMENT_06=c:\Anaconda2
	SET REPLACEMENT_07=c:\Anaconda3

	set "VIRTUAL_ENV=%DST_PATH%"
	rem ECHO VIRTUAL_ENV0=%VIRTUAL_ENV%

	if defined _OLD_VIRTUAL_PROMPT (
	    set "PROMPT=%_OLD_VIRTUAL_PROMPT%"
	) else (
	    if not defined PROMPT (
	        set "PROMPT=$P$G"
	    )
	    set "_OLD_VIRTUAL_PROMPT=%PROMPT%"
	)

	IF DEFINED VIRTUAL_ENV_NAME (
		rem ECHO VIRTUAL_ENV_NAME=%VIRTUAL_ENV_NAME%
		rem set "PROMPT=(%VIRTUAL_ENV_NAME%) %PROMPT%"
		set "PROMPT=[101;93m(%VIRTUAL_ENV_NAME%)[0m %PROMPT%"
		rem ECHO PROMPT0=%PROMPT%
	) else (
		rem ECHO PROMPT1=%PROMPT%
		SET /P VIRTUAL_ENV_NAME="VIRTUAL ENV NAME: "
	)

	if defined _OLD_VIRTUAL_PYTHONHOME goto ENDIFVHOME
	    set "_OLD_VIRTUAL_PYTHONHOME=%PYTHONHOME%"


:ENDIFVHOME
set PYTHONHOME=
if not defined _OLD_VIRTUAL_PATH goto ENDIFVPATH1
    set "PATH=%_OLD_VIRTUAL_PATH%"

:ENDIFVPATH1
if defined _OLD_VIRTUAL_PATH goto ENDIFVPATH2
    set "_OLD_VIRTUAL_PATH=%PATH%"

:ENDIFVPATH2
rem ECHO SRC_PATH=%SRC_PATH%
rem ECHO DST_PATH=%DST_PATH%

FOR %%i in (
	%REPLACEMENT_01%
	%REPLACEMENT_02%
	%REPLACEMENT_03%
	%REPLACEMENT_04%
	%REPLACEMENT_05%
	%REPLACEMENT_06%
	%REPLACEMENT_07%
) DO (
	CALL SET PATH=%%PATH:%%i=%SRC_PATH%%%
)

rem CALL SET PATH=%%PATH:%SRC_PATH%=%DST_PATH%%%
rem ECHO PATH=%PATH%
rem set "PATH=%VIRTUAL_ENV%\Scripts;%PATH%"
rem set PATH="%PATH:c:\ProgramData\Anaconda2=C:\ProgramData\Python37%"
goto end

:end